yarnPath: .yarn/releases/yarn-3.3.0.cjs
packageExtensions:
  eslint-config-react-app@*:
    peerDependencies:
      eslint-plugin-flowtype: ^5.8.2
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
  sundaes-on-demand@*:
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"
      "@testing-library/dom": "*"
      eslint: "*"
      eslint-plugin-import: "*"
      eslint-plugin-react: "*"
      eslint-plugin-react-hooks: "*"
      "@popperjs/core": "*"
  react-scripts@*:
    peerDependencies:
      "@babel/plugin-syntax-flow": "*"
      "@babel/plugin-transform-react-jsx": "*"


